// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMwEfmH2BCa-8Kf4X2eodVfVxnEVq9YV0',
    appId: '1:624124730943:web:0a8738bb556f085fcc228a',
    messagingSenderId: '624124730943',
    projectId: 'mchat-8d6ef',
    authDomain: 'mchat-8d6ef.firebaseapp.com',
    databaseURL: 'https://mchat-8d6ef.firebaseio.com',
    storageBucket: 'mchat-8d6ef.appspot.com',
    measurementId: 'G-B3M69NWSE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRwVENaOQIa-uoc8eEIjm6Z9v80ovycz0',
    appId: '1:624124730943:android:fd809de6e87b176acc228a',
    messagingSenderId: '624124730943',
    projectId: 'mchat-8d6ef',
    databaseURL: 'https://mchat-8d6ef.firebaseio.com',
    storageBucket: 'mchat-8d6ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZK7Lx4fAKNU12B6Qtc8sDSgyrg11Lus',
    appId: '1:624124730943:ios:2aa8bceb6351007fcc228a',
    messagingSenderId: '624124730943',
    projectId: 'mchat-8d6ef',
    databaseURL: 'https://mchat-8d6ef.firebaseio.com',
    storageBucket: 'mchat-8d6ef.appspot.com',
    iosClientId: '624124730943-b03tkddb7q0j8667bj0ngd2d264i8r2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.yhaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxZK7Lx4fAKNU12B6Qtc8sDSgyrg11Lus',
    appId: '1:624124730943:ios:2aa8bceb6351007fcc228a',
    messagingSenderId: '624124730943',
    projectId: 'mchat-8d6ef',
    databaseURL: 'https://mchat-8d6ef.firebaseio.com',
    storageBucket: 'mchat-8d6ef.appspot.com',
    iosClientId: '624124730943-b03tkddb7q0j8667bj0ngd2d264i8r2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.yhaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMwEfmH2BCa-8Kf4X2eodVfVxnEVq9YV0',
    appId: '1:624124730943:web:773ef4c57845b385cc228a',
    messagingSenderId: '624124730943',
    projectId: 'mchat-8d6ef',
    authDomain: 'mchat-8d6ef.firebaseapp.com',
    databaseURL: 'https://mchat-8d6ef.firebaseio.com',
    storageBucket: 'mchat-8d6ef.appspot.com',
    measurementId: 'G-C6VL4VTPDV',
  );
}
